In [2]:
import os
os.environ["PATH"]+=os.pathsep+'C:/Program Files/Graphviz/bin'

In [2]:
import sklearn
print(sklearn.__version__)

0.24.2


## 붗꽃 품종 예측하기
### 데이터??
#### 알고리즘??


In [5]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import pandas as pd

iris = load_iris()
iris_data=iris.data
print('iris feature값 :',iris_data)
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state = 11)


iris feature값 : [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1

In [6]:
df_clf = DecisionTreeClassifier(random_state = 11)
df_clf.fit(x_train, y_train)
pred = df_clf.predict(x_test)
print('예측 정확도: {0:4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.933333


In [13]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])


붓꽃 데이터 세트 크기: 150


In [23]:
n_iter = 0

for train_index, test_index in kfold.split(features):
    
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    n_iter+=1
    
    accuracy = np.round(accuracy_score(y_test, pred),4)
    print("test=:",y_test)
    print("pred=:", pred)
    train_size= x_train.shape[0]
    test_size = x_test.shape[0]
    
    print('\n#{0} 교차 검증 정확도:{1}, 학습 데이터 크기: {2}, 검증 데이터 크기 {3}'.format(n_iter,
                                                                      accuracy,
                                                                      train_size,
                                                                      test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    
    print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))

test=: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
pred=: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

#1 교차 검증 정확도:1.0, 학습 데이터 크기: 120, 검증 데이터 크기 30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

## 평균 검증 정확도: 0.9285714285714286
test=: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
pred=: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 1 1]

#2 교차 검증 정확도:0.9667, 학습 데이터 크기: 120, 검증 데이터 크기 30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

## 평균 검증 정확도: 0.9311133333333333
test=: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
pred=: [1 1 1 1 1 1 1 1 1 1 2 1 2 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1]

#3 교차 검증 정확도:0.8667, 학습 데이터 크기: 120, 검증 데이터 크기 30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

## 평균 검증 정확도: 0.9270875000000001
test=: [1 1 1 1 

In [21]:
a= np.round(5.6676767, 4)
print(a)

5.6677


In [25]:
import pandas as pd 
iris = load_iris()

iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()


0    50
1    50
2    50
Name: label, dtype: int64

In [27]:
iris_df['label']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: label, Length: 150, dtype: int32

In [29]:
kfold = KFold(n_splits=3)

n_iter =0
for train_index, test_index in kfold.split(iris_df):
    n_iter+=1
    print(test_index)
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## 교차검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())
    


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
## 교차검증: 1
학습 레이블 데이터 분포:
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    50
Name: label, dtype: int64
[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]
## 교차검증: 2
학습 레이블 데이터 분포:
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    50
Name: label, dtype: int64
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
## 교차검증: 3
학습 레이블 데이터 분포:
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    50
Name: label, dtype: int64


In [36]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits =5)
n_iter =0

for train_index, test_index in skf.split(iris_df,iris_df['label']):
    n_iter+=1

    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## 교차검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())
    
    print('\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
    print('## 평균 검증 정확도:', np.mean(cv_accuracy))

## 교차검증: 1
학습 레이블 데이터 분포:
 0    40
1    40
2    40
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    10
1    10
2    10
Name: label, dtype: int64

## 교차 검증별 정확도: [1.     1.     1.     1.     0.9667 0.8667 0.9333 0.7333 1.     0.9667
 0.8667 0.9333 0.7333 1.     0.9667 0.8667 0.9333 0.7333]
## 평균 검증 정확도: 0.9166666666666666
## 교차검증: 2
학습 레이블 데이터 분포:
 0    40
1    40
2    40
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    10
1    10
2    10
Name: label, dtype: int64

## 교차 검증별 정확도: [1.     1.     1.     1.     0.9667 0.8667 0.9333 0.7333 1.     0.9667
 0.8667 0.9333 0.7333 1.     0.9667 0.8667 0.9333 0.7333]
## 평균 검증 정확도: 0.9166666666666666
## 교차검증: 3
학습 레이블 데이터 분포:
 0    40
1    40
2    40
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    10
1    10
2    10
Name: label, dtype: int64

## 교차 검증별 정확도: [1.     1.     1.     1.     0.9667 0.8667 0.9333 0.7333 1.     0.9667
 0.8667 0.9333 0.7333 1.     0.9667 0.8667 0.9333 0.7333]
## 평균 검증 정확도: 0.9166666666666666
## 교차검증: 4
학습 레이블 데이터 분포:
 0    40
1 

In [3]:
from sklearn.tree import export_graphviz

export_graphviz(dt_clf, out_file = "tree.dot", class_names=iris_data.target_names , \
feature_name = iris_data.feature_names, impurity = True, filled = True)

import graphviz

with open("tree.dot")as f:
    dot_graph = f.read()
graphviz.Source(got_graph)

NameError: name 'dt_clf' is not defined

In [1]:
lr_clf=LogisticRegression(max_iter=3000)

NameError: name 'LogisticRegression' is not defined